# Generated by Django 5.1.7 on 2025-03-28 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart_item',
            new_name='Item',
        ),
    ]
